<template>
	<div class="card mb-4 mt-8 text-left border-solid border">
		<h5 class="card-header text-xl ledaing-10 ">{{ json.name }} </h5>
		<div class="card-body p-4">
			<p class="my-2">Choose a command:</p>
			<div name="selectBox" class="form-select">
				<p class="w-full text-sm cursor-pointer" v-for="option in json.options" :key="option.key"
					@click="handleSelectChange(option.key)" :title="option.name">
					{{ option.name }}
				</p>
			</div>

			<div class="mb-2">
				<video ref="videoPlayer" width="100%" preload="metadata" playsinline="" controls="">
					<source :src="json.videoName" type="video/mp4">
				</video>
			</div>

			<div class="row" id="content_draw_1">
				<div>
					<p>Code generated by our Language Model Program:
					</p>
				</div>
				<div class="w-full">
					<!-- <highlightjs language="xml" :code="json.options[activeIndex - 1].code"></highlightjs> -->
					<highlightjs class="code-container" language="xml" :code="code"></highlightjs>
				</div>
			</div>
		</div>
	</div>
</template>

<script setup>
import { ref, defineProps, onMounted } from 'vue'

const videoPlayer = ref(null)
const activeIndex = ref(1)
const code = ref('')
const props = defineProps({
	json: Object,
	index: Number
})
onMounted(() => {
	getCode()
})
const getCode = () => {
	loadTxtFile(`./code/video${props.index}/${activeIndex.value}.txt`, function (data) {
		code.value = data
	});
}
const handleSelectChange = (val) => {
	// console.log(val)
	const timePoint = props.json.options[val - 1].time
	activeIndex.value = val
	if (videoPlayer.value) {
		videoPlayer.value.currentTime = timePoint
		videoPlayer.value.play()
	}
	getCode()

}
const loadTxtFile = (url, callback) => {
	var xhr = new XMLHttpRequest();
	xhr.open('GET', url, true);
	xhr.onreadystatechange = function () {
		if (xhr.readyState === 4 && xhr.status === 200) {
			callback(xhr.responseText);
		}
	};
	xhr.send();
}

</script>

<style>
.card {
	position: relative;
	display: flex;
	flex-direction: column;
	min-width: 0;
	word-wrap: break-word;
	background-color: #f8f9fa;
	background-clip: border-box;
	border: 1px solid rgba(0, 0, 0, .125);
	border-radius: .25rem;
}

.card-header {
	padding: .5rem 1rem;
	margin-bottom: 0;
	background-color: rgba(0, 0, 0, .03);
	border-bottom: 1px solid rgba(0, 0, 0, .125);
}

.card-body {
	flex: 1 1 auto;
	padding: 1rem 1rem;
}

.form-select {
	display: block;
	width: 100%;
	height: 150px;
	overflow-x: auto;
	padding: .375rem 0 1rem .75rem;
	-moz-padding-start: calc(0.75rem - 3px);
	font-size: 1rem;
	font-weight: 400;
	line-height: 1.5;
	color: #212529;
	background-color: #fff;
	background-repeat: no-repeat;
	background-position: right .75rem center;
	background-size: 16px 12px;
	border: 1px solid #ced4da;
	border-radius: .25rem;
	transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
}
.form-select p:hover{
	background: #eee;
}

.form-select[multiple],
.form-select[size]:not([size="1"]) {
	/* padding-right: .75rem; */
	background-image: none;
}

pre code.hljs {
	line-height: 22px;
	font-size: 14px;
}
.code-container {
	width: 100%;
    white-space: pre-wrap;
    word-wrap: break-word;
}
</style>
